### ISSUE TITLE
Delete watermark on every files

### ISSUE THREAD

**Issue by stylersnico** [elcodigok/wphardening#92]
Hi,

I just found than this software just act like malware.

It adds something like : `/* WP Hardening - 2016-05-07 11:28:00.846819 */` in every file he touches.

The problem is, some plugins like divi booster use .txt file to generate custom footer and this simply kill custom footer of every website he touches by adding this text in the footer.

How can we remove this feature? Is it really useful? 

Have a gday,

Nicolas

**Comment by elcodigok** [comment]
Hi Nicolas

Thank you very much for asking for this feature.

This watermark that add to txt files is that tools like wpscan when performing some verification does not by its content but by the value of its md5 or sha.

For this reason it is necessary to change the signatures are different.

If I agree that the legend or watermark should change and not give much information.

Regards!
